### PR TITLE
234 GitHub actions ci

### LINKED ISSUE #234: Move from travis-ci to github actions
For detailed suggestions on code testing in GDL, see #103 .

To help with the transition, see [Github doc](https://docs.github.com/en/actions/migrating-to-github-actions/migrating-from-travis-ci-to-github-actions)

### PR DESCRIPTION
**Pull request by remtav**
closes #234

### CODE REVIEW

**Review by CharlesAuthier — APPROVED** [review]
Thanks for the clean up

**Review by ymoisan — APPROVED** [review]

**Review by mpelchat04 — APPROVED** [review]

**Comment by mpelchat04** [comment]
Some files deleted here are also deleted in PR #239

**Review by victorlazio109 — APPROVED** [review]
Cool!

**Comment by remtav** [comment]
> Some files deleted here are also deleted in PR #239

True. I realized this afterwards. We'll see how git manages this conflict. Shouldn't be too problematic. I'll merge this since approval has been given and deal with this while merging PR #239

**Pull request merged**
