### PR TITLE
add solaris utilities useful to GDL. Integrates bugfixes and features…

### LINKED ISSUE #216: Images_to_samples.py (hdf5s) --> data_to_tiles.py: add gdal library in conda
Onboarding solaris requires GDL to use gdal as a python library (not just from the OS). This will require us to update environment.yml to create a functional conda env with this new dependency.
For context, see #215

### LINKED ISSUE #233: Solaris utilities: temporary onboarding
# [Data_to_tiles transition](https://github.com/NRCan/geo-deep-learning/issues/215)
In order to facilitate the transition from hdf5 samples to plain .tif (imagery) and .geojson (ground truth) samples (aka tiles), some utilities from the solaris library must be temporarily onboarded.

Once [solaris v0.5 is out](https://github.com/CosmiQ/solaris/projects/1), some PRs will be made to the [main solaris repo](https://github.com/CosmiQ/solaris) in order to merge GDL's needs with the state of solaris at that point.

# Why temporarily onboard, then remove?

­­Note those of you wondering why we shouldn't just use solaris as it is now and adapt once it's updated:
Since solaris was previously considered as dead, the onborading and modification of solaris to meet GDL's needs had already advanced with many hours of bugfixing and adapting. Therefore, it will be easier to add the relevant solaris utilities to GDL directly, make PRs to ensure a seamless transition, then remove those utilities from GDL's repo.

### PR DESCRIPTION
**Pull request by remtav**
fixes #233 
fixes #216

First step towards sampling transition from hdf5s to plain .tif and .geojson tiles: #215

### CODE REVIEW

**Review by victorlazio109 — COMMENTED** [review]
Is everyone committed to this transition?

**Comment by CharlesAuthier** [comment]
I think adding a README can  help

**Comment by remtav** [comment]
The following information will be added to README:
Code reference: https://github.com/CosmiQ/solaris/tree/main/solaris (relevant subfolders: "eval", "raster", "tile", "utils")
Documentation: https://solaris.readthedocs.io/en/latest/
Example usage of solaris to create masks: https://solaris.readthedocs.io/en/latest/tutorials/notebooks/api_masks_tutorial.html

**Comment by remtav** [comment]
The GDL team has decided to wait for [solaris to release v0.5.0](https://github.com/CosmiQ/solaris/projects/1) and skip this temporary onboarding.

Meanwhile, a branch with the solaris material and tiling to .tifs and .geojson is on my fork: [215-solaris-tiling2](https://github.com/remtav/geo-deep-learning/tree/215-solaris-tiling2)

**Pull request closed without merging**
